travis:
  secure:
    BINSTAR_TOKEN: JbKPvju21/Jnc0gY0WyQo53YuJLLkpFlVrOPlc+jJGShdudeF3J2xew3bBSibfOUflU2AsBUEOHL8H4cUB7UZAnjq9Z471AAPo5QfOtEBpDN8bd1iHj/3MNINemxJZIHgS7HXfTMJL1Oo8g5HsdkNq2s5yU0TNsTnfINP8vyznfJ3dzPIRaHqi9aYdpwc5SE/lOmJNvGEktN4lXc3s+luYpfbdpRrnwuImw4pu6BlYaL6IqeYSVJIxaZwh4tZAddxXgZTJHj3eUnKEj3mj0F0TNsAq9IUoxYR0+v+lF0ePP9txBDaLCKQxLnIQyRgdbHXD/MNGWvlSD1ALOBm9cxzeFv2d+kTTwIAzFUbdqAm/LhB2Tqqq8Lohj0C973C6aEoLpZtm5tB4TkskaWlA7iDeUF02CRIBb+SVoz9O/IL5QhXgu1HwwAIfx8edQfMqgnpkySZKfSQyOowgEwpXEdPMml2Tw77HFrAyY4vRR9xuplXrNciBKW5I/hL6LcMGcw0NhM0nop53tdVZ9RAg8o4yj45NMcfwllFV9Sbi6WN/k/+lw1tlX3aBkkA9lbbAS4I4zxtY97DThIG4B5iEcVRXrKc8dYyjF4DK8mTAi9V4FPM1wq0xoSdTrIWX0focA9RuuXocORSVSROh7ehT2CEN/7HntW3VtUkmnnzUzzcFg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
