travis:
  secure:
    BINSTAR_TOKEN: Da3J8kE18gD7z6Co2HhVuZ76yz4RSst67mPqzhkwxAqRCseRxDQbZHVib+UprU6AiTuihJu9p36+JvLs9pK1l2a/sSAM1ra7lrt2kPwotYeYUSVWb1s0d+1e/zONnXkrVvczqZc8uXs80kTDhY5F3y0vHKi3AKmzS6Gt/Kb7YArXb8fCS2a1dy4qVmnl7n0PYqmNCCSKLmzMDXZO2NFJpYe0neTl+0QayzgK/0YFmF3hV2nLvQDDsotsG/p1omHXgnR/yH+AGX1B2oZZZqCTVExADn6+cLgdXGnvITHNsCYEQl7uTYlGtRMjQXMN/AvSYzA9afnOxB90YH+Qk4zpex55LJz5Y0JNjXErVH16XfbLpC1+Z1QSyy+iWwU7N8nfBan96Q3XkaaRcKn7pjLSQW6EJUHwdZ/vdm4jknVT8R53SXPBJulIjIt6tUetgy9RECFTGoq0jTyp3m9rn9I3pbdsa+O0hXERwMKXe44wCDbr/VbO2ANBB84Lw8tR1ANC7M1iztxTuHoxKLKKV6DbEVjd/eFUSvoh4L2UqMfWi7kHNTQ+XaoGlfNsZtY2kH1lBu6tASWpTnFHaBzPmwstvi23jBP4sdINaROmctHjDcPEoNhZqEaIH63XIEnCDK9T5tR2Z397KZBxTLkIJ8AZSdLSivNEsrxlMuJzs9g7zdA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
